# cloudbuild.yaml
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/ott-event-pipeline:latest', './scripts/streaming']
  
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/ott-event-pipeline:latest']
  
  # Create the template spec file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        cat > /workspace/event_pipeline_spec.json << EOF
        {
          "image": "gcr.io/${PROJECT_ID}/ott-event-pipeline:latest",
          "sdk_info": {
            "language": "PYTHON"
          }
        }
        EOF
  
  # Create the Dataflow Flex Template
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'dataflow', 'flex-template', 'build',
      'gs://${_PROCESSED_DATA_BUCKET}/dataflow/templates/event_pipeline.json',
      '--image', 'gcr.io/${PROJECT_ID}/ott-event-pipeline:latest',
      '--sdk-language', 'PYTHON',
      '--metadata-file', '/workspace/event_pipeline_spec.json'
    ]

# Define substitution variables with defaults
substitutions:
  _PROCESSED_DATA_BUCKET: "default-bucket-name"  # Changed to match GitHub secret name

images:
  - 'gcr.io/${PROJECT_ID}/ott-event-pipeline:latest'