name: Deploy DAGs to Cloud Composer

on:
  push:
    branches: [ main ]
    paths:
      - 'dags/**'

jobs:
  deploy-dags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage python-dotenv
    
    - name: Create .env file
      run: |
        echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" > .env
        echo "RAW_DATA_BUCKET=${{ secrets.RAW_DATA_BUCKET }}" >> .env
        echo "PROCESSED_DATA_BUCKET=${{ secrets.PROCESSED_DATA_BUCKET }}" >> .env
        echo "ARCHIVE_DATA_BUCKET=${{ secrets.ARCHIVE_DATA_BUCKET }}" >> .env
        echo "BIGQUERY_DATASET=${{ secrets.BIGQUERY_DATASET }}" >> .env
        echo "GCP_REGION=${{ secrets.GCP_REGION }}" >> .env
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    
    - name: Deploy DAGs to Composer
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_COMPOSER_BUCKET: ${{ secrets.GCP_COMPOSER_BUCKET }}
      run: |
        python scripts/deploy_dags_to_composer.py